name: 36 - Local Action

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Necessary to access local action
      
      - name: Setup AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          
      - name: generate file
        run: echo "hola" > /tmp/a.txt
      

      - name: Local Action Call
        id: local-action
        uses: ./.github/actions/local-action
        with:
          name: "World"
          
      - name: Local Action Output
        run: echo "${{ steps.local-action.outputs.random }}"
