name: 36 - Local Action

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Necessary to access local action

      - name: Setup AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          
      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -f /tmp/ssh_id_gh -N ""
          echo "SSH_KEY_PATH=/tmp/ssh_id_gh.pub" >> $GITHUB_ENV

      - name: Local Action Call
        id: local-action
        uses: ./.github/actions/local-action
        with:
          instance_name: "monai-build"
          key_name: "monai-build-key"
          ec2_role: "ec2-role"
          ssh_key_path: "/tmp/ssh_id_gh.pub"
          
      - name: Local Action Output ID, VM name
        run: |
          echo "Instance ID: ${{ steps.local-action.outputs.instance_id }}"
          echo "VM Name: ${{ steps.local-action.outputs.vm_name }}"
