name: Display File Workflow

on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string

jobs:
  display-file:
    runs-on: ubuntu-latest

    steps:
    - name: Write text to a.txt
      run: echo "${{ inputs.text }}" > /tmp/a.txt

    - name: Display contents of a.txt
      run: cat /tmp/a.txt
