name: build_and_push_models

on: workflow_dispatch

env:
  AWS_REGION: "us-east-1"
  MONAI_APP_PATH: "monai-deploy-app-sdk/examples/apps/ai_spleen_seg_app"
  MONAI_APP_CONFIG: "monai-deploy-app-sdk/examples/apps/ai_spleen_seg_app/app.yaml"
  MONAI_MODEL_ZIP: "spleen_model.zip"
  VERSION: "0.6.0"
  PYTHON_VERSION: "3.8"
  

jobs:
  setup_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          
      - name: Check for existing EC2 instance and terminate if exists
        id: check_ec2_instance
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=monai-build" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text)
          if [ ! -z "$INSTANCE_ID" ]; then
            echo "Found existing EC2 instance with ID $INSTANCE_ID. Terminating..."
            aws ec2 terminate-instances --instance-ids $INSTANCE_ID
            echo "Waiting for termination to complete..."
            aws ec2 wait instance-terminated --instance-ids $INSTANCE_ID
            echo "INSTANCE_TERMINATED=true" >> $GITHUB_ENV
          else
            echo "No existing EC2 instance found."
            echo "INSTANCE_TERMINATED=false" >> $GITHUB_ENV
          fi
          
      - name: Check for existing Key Pair and delete if exists
        id: check_key_pair
        run: |
          if aws ec2 describe-key-pairs --key-names "monai-deploy-key" ; then
            aws ec2 delete-key-pair --key-name "monai-deploy-key"
            echo "KEY_DELETED=true" >> $GITHUB_ENV
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false 

      - name: Initialize a new Terraform working directory
        run: terraform init

      - name: Format Terraform configuration files
        run: terraform fmt

      - name: Check Terraform configuration files format
        run: terraform fmt -check

      - name: Generate unique SSH Key
        if: steps.check_key_pair.outputs.KEY_DELETED == 'true' || steps.check_key_pair.outputs.KEY_DELETED == ''
        run: ssh-keygen -t rsa -f /tmp/ssh_id_gh -N ""

      - name: Terraform Destroy
        if: ${{ always() }}
        run: terraform destroy -auto-approve

      - name: Terraform Apply
        run: terraform apply -auto-approve
        
      - name: Assign IAM Role to EC2 Instance
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=monai-build" --query "Reservations[0].Instances[0].InstanceId" --output text)
          aws ec2 associate-iam-instance-profile --instance-id $INSTANCE_ID --iam-instance-profile Name=ec2-role

      - name: Get IP address
        run: |
          IP=$(terraform output -raw instance_public_ip)
          echo "AWS_IPADDRESS=$IP" >> $GITHUB_ENV
          echo "VM IP Address: $IP"
      
      - name: Get VM name
        run: |
          VM_NAME="ubuntu@${{ env.AWS_IPADDRESS }}"
          echo "VM_NAME=$VM_NAME" >> $GITHUB_ENV
          echo "Constructed VM Name: $VM_NAME"
      
      - name: Test connection
        run: |
          echo "Attempting to connect to: ${{ env.VM_NAME }}"
          for i in {1..10}; do
            ssh -i /tmp/ssh_id_gh -o StrictHostKeyChecking=no -o ConnectTimeout=10 "${{ env.VM_NAME }}" "uname -a" && break || sleep 10
          done
          
      - name: Cloning repository
        env:
          REPO_URL: ${{ github.repository }}
        run: |
          ssh -i /tmp/ssh_id_gh $VM_NAME "git clone --branch main --depth 1 https://github.com/${REPO_URL}.git"
     
      - name: Downloading model
        run: |
          ssh -i /tmp/ssh_id_gh $VM_NAME << EOF
          wget https://github.com/${{ github.repository }}/releases/latest/download/${{ env.MONAI_MODEL_ZIP }} -O model.zip
          EOF
        
      - name: Unzip the model
        run: ssh -i /tmp/ssh_id_gh $VM_NAME "unzip -o model.zip"

      - name: Package MONAI deploy app
        run: |
          ssh -i /tmp/ssh_id_gh $VM_NAME << EOF
          sudo su - ubuntu
          . /home/ubuntu/anaconda3/etc/profile.d/conda.sh
          conda activate monai
          monai-deploy package ${{ env.MONAI_APP_PATH }} \
            --config ${{ env.MONAI_APP_CONFIG }} \
            --tag seg_app:latest \
            --models model.ts \
            --platform x64-workstation \
            -l DEBUG
          EOF

      - name: Login to AWS ECR
        run: |
           ssh -i /tmp/ssh_id_gh $VM_NAME "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
          
      - name: Tag Docker Image
        run: |
          IMAGE_NAME="monai:latest"
          DOCKER_IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${IMAGE_NAME}"
          ssh -i /tmp/ssh_id_gh $VM_NAME "docker tag seg_app-x64-workstation-dgpu-linux-amd64:latest $DOCKER_IMAGE"
          
      - name: Push Docker Image
        run: |
          IMAGE_NAME="monai:latest"
          DOCKER_IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${IMAGE_NAME}"
          ssh -i /tmp/ssh_id_gh $VM_NAME "docker push $DOCKER_IMAGE"
