name: Setup Lambda and S3

on: workflow_dispatch

jobs:
  setup_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Update setup.sh with secrets
        run: |
          cd setup_lambda
          sed -i 's|ROLE_ARN=""|ROLE_ARN="${{ secrets.AWS_LAMBDA_ROLE }}"|' setup.sh
          sed -i 's|REGION=""|REGION="${{ secrets.AWS_REGION }}"|' setup.sh
          sed -i 's|BUCKET_NAME=""|BUCKET_NAME="${{ secrets.AWS_S3_BUCKET }}"|' setup.sh
          sed -i 's|ACCOUNT_ID=""|ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}"|' setup.sh

      - name: Run setup.sh
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Clean up
        run: |
          rm function.zip
          rm s3_event_configuration.json
          rm setup.sh
          rm lambda_function.py
