name: Stop EC2 Instance

on:
  workflow_dispatch:
    inputs:
      instanceId:
        description: 'EC2 Instance ID to stop'
        required: true

jobs:
  stop-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 Instance
        run: aws ec2 stop-instances --instance-ids ${{ github.event.inputs.instanceId }}
